export const ActionTypes = {
  SET_ARTICLES: "SET_ARTICLES",
  SET_ARTICLES_QUERY: "SET_ARTICLES_QUERY",
  SET_SINGLE_ARTICLE: "SET_SINGLE_ARTICLE",


  SELECT_ARTICLES: "SELECT_ARTICLES",
  REMOVE_SELECT_ARTICLES: "REMOVE_SELECT_ARTICLES"
};