export const ActionTypes = {
  SET_ARTICLES: "SET_ARTICLES",
  SET_ARTICLES_QUERY: "SET_ARTICLES_QUERY",
  SET_SINGLE_ARTICLE: "SET_SINGLE_ARTICLE",

  SELECT_ARTICLES: "SELECT_ARTICLES",
  REMOVE_SELECT_ARTICLES: "REMOVE_SELECT_ARTICLES",
  
  SET_DARK_MODE: "SET_DARK_MODE",
  SET_LIGHT_MODE: "SET_LIGHT_MODE",
  
  SWITCH_SIDEBAR_MOBILE: "SWITCH_SIDEBAR_MOBILE",
  CLOSE_SIDEBAR_MOBILE: "CLOSE_SIDEBAR_MOBILE"
};